server:
  port: 8181


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  dubbo:
    application:
      name: member-web-consumer  
    registry:
      address: zookeeper://192.168.88.29:2181
    scan: com.startdt
